# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02a8429c587e39eb862ab6ebc85de027dc37500c3e9fa6a264c9da37de8acc92de336c0d1a4dabde9264a0f1914ccd30c0652ea1dcf78b7ae05ed31634115320

test:
  secret_key_base: a906945deaff8103947d6443c9c8beadf320841b20deecbbd3e78cd7ad3a0674e1f137070632db73ecc6f20dedb7848e2a1f73560365890848cc144caaaf8644

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
